from kedro.pipeline import Pipeline, node

from centromonitoreo_mineria.pipelines.train_mining_binary_rf.nodes import (
    build_mining_binary_feature_importance,
    build_mining_binary_random_forest_metadata,
    build_testing_dataset,
    build_training_dataset,
    evaluate_mining_binary_random_forest,
    plot_mining_binary_confusion_matrix,
    plot_mining_binary_feature_importance,
    predict_mining_binary_random_forest,
    train_mining_binary_random_forest,
    validate_mining_binary_random_forest_config,
)


def create_pipeline(**kwargs) -> Pipeline:
    """Creates the Kedro pipeline for binary mining Random Forest."""
    return Pipeline(
        [
            node(
                func=validate_mining_binary_random_forest_config,
                inputs="params:mining_binary_random_forest",
                outputs="mining_binary_random_forest_config",
                name="validate_mining_binary_random_forest_config_node",
            ),
            node(
                func=build_training_dataset,
                inputs=[
                    "training_sentinel2_features",
                    "mining_binary_random_forest_config",
                ],
                outputs="mining_binary_training_dataset",
                name="build_mining_binary_training_dataset_node",
            ),
            node(
                func=build_testing_dataset,
                inputs=[
                    "testing_sentinel2_features",
                    "mining_binary_random_forest_config",
                ],
                outputs="mining_binary_testing_dataset",
                name="build_mining_binary_testing_dataset_node",
            ),
            node(
                func=train_mining_binary_random_forest,
                inputs=[
                    "mining_binary_training_dataset",
                    "mining_binary_random_forest_config",
                ],
                outputs="mining_binary_random_forest_model",
                name="train_mining_binary_random_forest_node",
            ),
            node(
                func=predict_mining_binary_random_forest,
                inputs=[
                    "mining_binary_random_forest_model",
                    "mining_binary_testing_dataset",
                    "mining_binary_random_forest_config",
                ],
                outputs="mining_binary_predictions",
                name="predict_mining_binary_random_forest_node",
            ),
            node(
                func=evaluate_mining_binary_random_forest,
                inputs=[
                    "mining_binary_predictions",
                    "mining_binary_random_forest_config",
                ],
                outputs="mining_binary_metrics",
                name="evaluate_mining_binary_random_forest_node",
            ),
            node(
                func=build_mining_binary_feature_importance,
                inputs=[
                    "mining_binary_random_forest_model",
                    "mining_binary_random_forest_config",
                ],
                outputs="mining_binary_feature_importance",
                name="build_mining_binary_feature_importance_node",
            ),
            node(
                func=plot_mining_binary_confusion_matrix,
                inputs=[
                    "mining_binary_metrics",
                    "mining_binary_random_forest_config",
                ],
                outputs="mining_binary_confusion_matrix_plot_metadata",
                name="plot_mining_binary_confusion_matrix_node",
            ),
            node(
                func=plot_mining_binary_feature_importance,
                inputs=[
                    "mining_binary_feature_importance",
                    "mining_binary_random_forest_config",
                ],
                outputs="mining_binary_feature_importance_plot_metadata",
                name="plot_mining_binary_feature_importance_node",
            ),
            node(
                func=build_mining_binary_random_forest_metadata,
                inputs=[
                    "mining_binary_training_dataset",
                    "mining_binary_testing_dataset",
                    "mining_binary_metrics",
                    "mining_binary_confusion_matrix_plot_metadata",
                    "mining_binary_feature_importance_plot_metadata",
                    "mining_binary_random_forest_config",
                ],
                outputs="mining_binary_random_forest_metadata",
                name="build_mining_binary_random_forest_metadata_node",
            ),
        ]
    )
